name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  semu-linux:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        dependency:
          - none
          - libpulse-dev
          - libjack-jackd2-dev
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: cache external downloads
      uses: actions/cache@v4
      with:
        path: |
          Image
          rootfs.cpio
        key: external-${{ hashFiles('mk/external.mk') }}
        restore-keys: |
          external-
    - name: cache submodule builds
      uses: actions/cache@v4
      with:
        path: |
          mini-gdbstub/build
          minislirp/src/*.a
        key: ${{ runner.os }}-submodules-${{ hashFiles('.gitmodules', 'mini-gdbstub/**', 'minislirp/**') }}
        restore-keys: |
          ${{ runner.os }}-submodules-
    - name: install-dependencies
      run: |
            sudo apt-get update
            sudo apt-get install -y build-essential device-tree-compiler expect libasound2-dev libudev-dev
    - name: install sound multiplexer ${{ matrix.dependency }}
      if: matrix.dependency != 'none'
      run: |
            sudo apt-get install -y ${{ matrix.dependency }}
    - name: default build
      run: make
      shell: bash
    - name: automated test
      run: .ci/autorun.sh
      shell: bash
    - name: netdev test
      run: .ci/test-netdev.sh
      shell: bash
      if: ${{ success() }}

  semu-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: cache external downloads
      uses: actions/cache@v4
      with:
        path: |
          Image
          rootfs.cpio
        key: external-${{ hashFiles('mk/external.mk') }}
        restore-keys: |
          external-
    - name: cache submodule builds
      uses: actions/cache@v4
      with:
        path: |
          mini-gdbstub/build
          minislirp/src/*.a
        key: ${{ runner.os }}-submodules-${{ hashFiles('.gitmodules', 'mini-gdbstub/**', 'minislirp/**') }}
        restore-keys: |
          ${{ runner.os }}-submodules-
    - name: install-dependencies
      run: |
            brew install make dtc expect e2fsprogs
    - name: default build
      run: make
      shell: bash
    - name: automated test
      run: .ci/autorun.sh
      shell: bash

  coding_style:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: coding convention
      run: |
            sudo apt-get update
            sudo apt-get install -q -y clang-format-18
            .ci/check-format.sh
      shell: bash
